version: "3"

services:
  jscoq:
    build:
      context: .
      target: jscoq
      dockerfile: LocalDockerfile
    image: jscoq
    env_file:
      - .env
    ports:
      - "0.0.0.0:8080:8080"
    expose:
      - "8080"
    # volumes:
    #   - ${REPOSITORY}:/repository:ro
    #   - learn-ocaml-sync:/sync
    command: npx static-server -p 8080 _build/dist
    # command: npx http-server -p 8080 dist

  

  mongodb:
    image: mongo:latest
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: jscoq-data
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongodb_data_container:/etc/mongod.conf
      - mongodb_data_container:/docker-entrypoint-initdb.d/
      - mongodb_data_container:/data/db/
      - mongodb_data_container:/var/log/mongodb/


  nodejs:
    build: 
      context: node/
    expose:
      - "8000"
    ports: 
      - "0.0.0.0:8000:8000"
    environment:
      - PORT=8000
      - DB_CONN=mongodb://mongodb:27017/jscoq
    volumes:
      - ./node:/node/app
      - node_modules:/node/app/node_modules
    depends_on:
      - mongodb


volumes:
  mongodb_data_container:
  node_modules:
